hepsiburada:
  outputs:
    dev:
      dataset: komtas_model_poc
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/duygu/Desktop/komtas-dwh-modeling-key.json
      location: EU
      method: service-account
      priority: interactive
      project: hb-dataanalytics-prod
      threads: 1
      type: bigquery
  target: dev
